# Android Gradle CircleCI 2.0 configuration file
#
# https://circleci.com/docs/2.0/language-android/
version: 2
build:
  jobs:
    build:
      working_directory: ~/project/android
      docker:
        - image: circleci/android:api-27-alpha

      environment:
        JVM_OPTS: -Xmx3200m

      steps:
        - checkout : 
            path: ~/project
        - restore_cache:
            keys:
            - jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle"}}

        - run: 
            name: Grant execution to Docker for the gradlew file
            command: sudo chmod +x gradlew

        - run:
            name: Build Debug
            command: ./gradlew assembleDebug

        - store_artifacts:
            path: app/build/outputs/apk/debug/app-debug.apk
            destination: app-debug.apk

        - run:
            name: Run Tests
            command: ./gradlew lint test

        - store_artifacts:
            path: app/build/reports
            destination: reports

        - store_test_results:
            path: app/build/test-results

        - run:
            name: Uploading on Beta
            command: ./gradlew crashlyticsUploadDistributionDebug
            
workflows:
  version: 2
    build_and_test:
      jobs:
        build:
          working_directory: ~/project/android
          docker:
            - image: circleci/android:api-27-alpha

          steps:
            - run:
                name: Hello World Build
                command: echo "Hello World Build !"

        test:
          working_directory: ~/project/android
          docker:
            - image: circleci/android:api-27-alpha

          steps:
            - run:
                name: Hello World Tests
                command: echo "Hello World Tests !"

