# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
# https://circleci.com/docs/2.0/language-android/
version: 2
jobs:
  build:
    working_directory: ~/android
    docker:
      - image: circleci/android:api-26-alpha

    environment:
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - restore_cache:
          keys:
          - jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle"}}

      - run: 
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
        
      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_artifacts:
          path: ap/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results


